### ISSUE TITLE
Request for pretrained models

### ISSUE THREAD

**Issue by ShirinVafaei** [shaoyent/multimodal-elmo#4]
Hi! :)

The link for the pretrained models (google drive link) is not working. Is it possible to solve this issue and fix the link?

Thanks in advance.
Shirin

**Comment by shaoyent** [comment]
Hi Shirin,
Thanks for the heads up, I have fixed the link. 
The new link is https://drive.google.com/file/d/151rg0u3PSvPohYiXvHSOFb8TeB2O1LQI/view
